### ISSUE TITLE
Only seeing messages from ROBLOX

### ISSUE THREAD

**Issue by BubbyNX** [jmkd3v/rbx-pm-archiver#2]
Hello!

I was able to successfully run both the JSON and HTML formats of the command, but I am only seeing messages sent from ROBLOX since 2015 (my account was created in 2012, username changed in 2015).  It looks like it is filtering out a majority of my other messages, including a large chunk that were sent under my old username.  Is there a way to disable the filtering so that the script can catch all of the messages, instead of just the filtered ones?

Thanks for the awesome tool and I look forward to hearing back!

**Comment by jmkd3v** [comment]
This tool is only meant to archive Roblox **system messages**. Only system messages will be deleted on April 20th. Other messages will be saved.

If you want to archive these messages as well, you should make another issue requesting this feature!
