### ISSUE TITLE
client error thing when running json and html commands

### ISSUE THREAD

**Issue by jowllian** [jmkd3v/rbx-pm-archiver#3]
this is my first time using github so this is prolly my fault but when I try to run the json or html commands this shows up:
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://users.roblox.com/v1/users/authenticated')

**Comment by jmkd3v** [comment]
Make sure you pass your .ROBLOSECURITY token properly. You should log into your account on your web browser, open the Cookies window, and copy the entirety of the cookie, and pass it in with double-quotes.

If you scroll down, this article explains how to do it if you're confused: https://ro.py.jmk.gg/dev/roblosecurity/

**Comment by jowllian** [comment]
yo ty, it works now. Turns out i just accidentally added a character to the token lol
