### ISSUE TITLE
Requesting Feature to Archive Player Messages + Support For Previous Usernames!

### ISSUE THREAD

**Issue by BubbyNX** [jmkd3v/rbx-pm-archiver#4]
At this time, the tool archives system messages only as recent as the most recent username change.  I would love to see the addition of flags or a capability that can allow the tool to also archive **all player sent/received messages** as well as **support for previous usernames**!

**Comment by jmkd3v** [comment]
What do you mean by "only as recent as the most recent username change"?

**Comment by BubbyNX** [comment]
The messages that are downloaded from my PMs are only from after I changed my username, so there weren't any system messages addressed to my old ROBLOX username.

**Comment by jmkd3v** [comment]
I can't reproduce this bug - messages from before a username change appear fine on my accounts. This is a bug on Roblox's end and not something the tool can fix. If you want, you can make a new issue requesting the ability to archive player PMs as well.
