### ISSUE TITLE
TypeError: 'PosixPath'

### ISSUE THREAD

**Issue by RodricBr** [jmkd3v/rbx-pm-archiver#5]
Getting a type error when trying to execute the program (with or without using flags)

```console
Traceback (most recent call last):
  File "rbx_pm_archiver.py", line 22, in <module>
    template_loader = FileSystemLoader(searchpath=html_assets_path)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

**Comment by jmkd3v** [comment]
Hello. I'm not entirely sure why this is happening - could you try making sure your Python version is up to date (i'd recommend going for 3.9+ but 3.7+ should probably also work) and making sure you reinstall all of the necessary packages?

When you install the packages with `pip3` or with `python3 -m pip` or whatever, add the `--update` flag at the end to make sure you update to the newest versions available.

**Comment by RodricBr** [comment]
Sorry for the late answer, but in short, I had tested on my WSL (ubuntu 20.04), which is unsurprisingly buggy, but I managed to get it working, thanks!
