### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by patheticpeasant** [jmkd3v/rbx-pm-archiver#6]
i literally do not understand how to do this

is there a video i can follow?

**Comment by patheticpeasant** [comment]
okay i sort of now get it but it said command not found: py

**Comment by IDKhowToScript** [comment]
> okay i sort of now get it but it said command not found: py

Have you installed python? if not, install it https://www.python.org/

After installing, install pip here: https://pip.pypa.io/en/stable/installation/
